# Generated by Django 2.1.3 on 2018-11-03 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0002_auto_20181103_1611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='non_attendees',
            new_name='sponsors',
        ),
    ]
