# Generated by Django 2.1.3 on 2018-11-04 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0004_auto_20181103_2309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='country',
            new_name='street',
        ),
    ]
