# Generated by Django 2.1.3 on 2018-11-03 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('cause', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='media/')),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('summary', models.TextField()),
                ('attendees', models.ManyToManyField(blank=True, related_name='attendees', to=settings.AUTH_USER_MODEL)),
                ('group', models.ManyToManyField(blank=True, related_name='group', to=settings.AUTH_USER_MODEL)),
                ('non_attendees', models.ManyToManyField(blank=True, related_name='non_attendees', to=settings.AUTH_USER_MODEL)),
                ('organiser', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='organiser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
